### ISSUE TITLE
魏依燃：关于万家灯火智慧家园的论坛模块的产品原型图设计——第二版。

### ISSUE THREAD

**Issue by TonyHappyStyle** [wjdh-platform/our-plants#2]
@weiyiran0821 
相关issue链接：
任务总链接：https://github.com/wjdh-platform/our-plants/issues/22
后端开发：https://github.com/wjdh-platform/wjdh-platform/issues/12
UI设计：https://github.com/wjdh-platform/our-plants/issues/23
原型图设计：https://github.com/wjdh-platform/our-plants/issues/2
前端开发：https://github.com/wjdh-platform/our-plants/issues/24

**Comment by TonyHappyStyle** [comment]
需要你列一个工作计划，不然不知道你什么时候能做完

**Comment by weiyiran0821** [comment]
# 工作计划制定

## 制定人：魏依燃

## 是否可以判断任务的结束时间节点：是

节点名称|节点时间|
|:--|:--
开始|2020年1月7日9:00
结束|2020年1月11日17:00

耗费工时：

**Comment by TonyHappyStyle** [comment]
依燃已经发给了我第一版原型图https://lanhuapp.com/web/#/item/project/board/proto/edit/entry?sId=f8b61f35-4a47-4333-bd63-5108f85070b7&pid=b8657592-ab03-4992-88ba-dee499088b57&type=mobile
<b>（依燃下次记得自己把最新版本的原型图分享到issue里）</b>

# 1. 原型图中缺少个人页面的逻辑，需要增加个人页面

## 点击用户头像，进入个人页面

## 个人页面需要有1-头像、2-昵称、3-用户的发帖列表、4-回复列表、5-点赞列表。6-粉丝数量、7-我的粉丝（数量，点开进入列表）、8-我的关注（数量+点击进入列表）

### 其中用户的发帖列表要包含：帖子标题、回复数量、点赞数量、发帖时间。大致元素模式如同下图（图片来源于PC端某网站，仅供参考），他人的个人页面里，叫“Ta的帖子”；自己的个人页面里，叫“我的帖子”

![image](https://user-images.githubusercontent.com/25560961/104029287-c269ea00-5204-11eb-9f6f-675c0906e30c.png)

### 其中用户的回复列表要包含：回复的帖子的标题、回复的内容、回复的时间，大致元素类别如下图（图片来源于PC端某网站，仅供参考），他人的个人页面里，叫“Ta的回复”；自己的个人页面里，叫“我的回复”

![image](https://user-images.githubusercontent.com/25560961/104029460-f6dda600-5204-11eb-9445-2f8974eca9bb.png)

### 点赞列表与回复列表基本雷同，他人的个人页面里，叫“Ta的点赞”；自己的个人页面里，叫“我的点赞”。但是与回复列表不同的是，没有回复内容的展示。

### 进入他人页面后，部分功能名称修改：如Ta的粉丝，Ta的关注

**Comment by TonyHappyStyle** [comment]
# 3. 评论区的@人功能和回复列表里套一层二次回复列表功能，暂时放到第三版去开发。
这两个需要大量代码处理逻辑，这次先不开发了

![image](https://user-images.githubusercontent.com/25560961/104032563-4a51f300-5209-11eb-8968-125ec546635f.png)

**Comment by TonyHappyStyle** [comment]
# 第三版增加排序功能

最新回复和最新发帖。第二版我们就不加了，默认最新发帖。

**Comment by weiyiran0821** [comment]
https://lanhuapp.com/url/aYSsL
密码: Zwdq

蓝湖的链接  可查看第二版原型图设计

**Comment by TonyHappyStyle** [comment]
> https://lanhuapp.com/url/aYSsL
> 密码: Zwdq
> 
> 蓝湖的链接 可查看第二版原型图设计

我看不了，注册了也看不了，没有更方便的方式吗？比如导出一个文件之类的？这个太不方便了

**Comment by TonyHappyStyle** [comment]
# 1.增添四个按钮
# 2.增加回复通知页面
## 回复通知功能：就是别人回复该用户的帖子，他可以收到通知，有多少个查看回复，然后点击进入，看到回复列表，列表中包含的元素有：1.回复帖子的标题，2.回复的内容，3.回复者昵称和头像。
![image](https://user-images.githubusercontent.com/25560961/104118129-9adc6400-5361-11eb-9827-ac5c2fe10e4b.png)

**Comment by TonyHappyStyle** [comment]
更新完之后，重新发布一个“第二版”的预览，这次必须是能看的

**Comment by weiyiran0821** [comment]
![Uploading 原型图.jpg…]()
