### ISSUE TITLE
魏依燃：论坛UI设计。重点是对杨哲、穆总针对第一版和第二版原型设计，采纳有关的修改建议和功能增加删减后，进行的UI设计

### ISSUE THREAD

**Issue by TonyHappyStyle** [wjdh-platform/our-plants#23]
相关issue链接：
任务总链接：https://github.com/wjdh-platform/our-plants/issues/22
后端开发：https://github.com/wjdh-platform/wjdh-platform/issues/12
UI设计：https://github.com/wjdh-platform/our-plants/issues/23
原型图设计：https://github.com/wjdh-platform/our-plants/issues/2
前端开发：https://github.com/wjdh-platform/our-plants/issues/24

**Comment by TonyHappyStyle** [comment]
# 2. 去除关注功能（为了增快第一版的上线速度，后期会添加）
![image](https://user-images.githubusercontent.com/25560961/104027638-9fd6d180-5202-11eb-9558-e617c98e232f.png)

**Comment by weiyiran0821** [comment]
![Uploading 原型图.jpg…]()

**Comment by TonyHappyStyle** [comment]
传的图看不了，需要重新传

**Comment by weiyiran0821** [comment]
![原型图](https://user-images.githubusercontent.com/75015874/104554864-d33cb480-5677-11eb-8f3d-1870f7b717ad.jpg)

**Comment by weiyiran0821** [comment]
![论坛UI设计](https://user-images.githubusercontent.com/75015874/105000134-ee893480-5a68-11eb-8676-2638b67cc4bf.jpg)
