### ISSUE TITLE
魏依燃：疫情防控的体温登记功能和举报功能UI设计。

### ISSUE THREAD

**Issue by TonyHappyStyle** [wjdh-platform/our-plants#30]
关联任务：
后台开发：#31
前台开发：#32
UI设计：#30

魏依燃，记得把最后的UI图放到这里面来。

**Comment by weiyiran0821** [comment]
![上报体温](https://user-images.githubusercontent.com/75015874/104430035-2f90cd00-55c1-11eb-8c18-a0cf2715de5f.jpg)
![输入体温](https://user-images.githubusercontent.com/75015874/104430044-315a9080-55c1-11eb-92e3-d06fd600a8a8.jpg)
